#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <ctype.h>
#include <time.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <fcntl.h>
#include <signal.h>
#include <jansson.h>

#define MAX_HEADER_SIZE 16384
#define MAX_BODY_SIZE 1048576

typedef struct { int id; char *username; char *password; } User;

typedef struct { char token[65]; int user_id; int used; } Session;

typedef struct {
    int id; int user_id; char *title; char *description; int completed;
    char created_at[21]; char updated_at[21]; int used;
} Todo;

static User *users = NULL; static size_t users_len = 0, users_cap = 0; static int next_user_id = 1;
static Session *sessions = NULL; static size_t sessions_len = 0, sessions_cap = 0;
static Todo *todos = NULL; static size_t todos_len = 0, todos_cap = 0; static int next_todo_id = 1;

static void http_time_now_iso(char out[21]) { time_t t=time(NULL); struct tm gm; gmtime_r(&t,&gm); strftime(out,21,"%Y-%m-%dT%H:%M:%SZ",&gm);} 
static int secure_random_bytes(unsigned char *buf,size_t len){int fd=open("/dev/urandom",O_RDONLY); if(fd<0) return -1; size_t off=0; while(off<len){ssize_t r=read(fd,buf+off,len-off); if(r<0){if(errno==EINTR) continue; close(fd); return -1;} if(r==0){close(fd); return -1;} off+=(size_t)r;} close(fd); return 0;}
static void bytes_to_hex(const unsigned char *in,size_t len,char *out){static const char *hex="0123456789abcdef"; for(size_t i=0;i<len;i++){out[2*i]=hex[(in[i]>>4)&0xF]; out[2*i+1]=hex[in[i]&0xF];} out[2*len]='\0';}
static char* strdup_s(const char *s){ if(!s) return NULL; size_t n=strlen(s); char *p=malloc(n+1); if(!p) return NULL; memcpy(p,s,n+1); return p; }
static int is_valid_username(const char *u){ if(!u) return 0; size_t n=strlen(u); if(n<3||n>50) return 0; for(size_t i=0;i<n;i++){ if(!(isalnum((unsigned char)u[i])||u[i]=='_')) return 0; } return 1; }
static int is_valid_password(const char *p){ return p && strlen(p)>=8; }

static User* find_user_by_username(const char *username){ for(size_t i=0;i<users_len;i++){ if(users[i].id!=0 && strcmp(users[i].username,username)==0) return &users[i]; } return NULL; }
static User* find_user_by_id(int id){ for(size_t i=0;i<users_len;i++){ if(users[i].id==id) return &users[i]; } return NULL; }
static Session* find_session_by_token(const char *token){ if(!token) return NULL; for(size_t i=0;i<sessions_len;i++){ if(sessions[i].used && strcmp(sessions[i].token,token)==0) return &sessions[i]; } return NULL; }
static int remove_session_by_token(const char *token){ for(size_t i=0;i<sessions_len;i++){ if(sessions[i].used && strcmp(sessions[i].token,token)==0){ sessions[i].used=0; return 1; } } return 0; }
static Todo* find_todo_by_id(int id){ for(size_t i=0;i<todos_len;i++){ if(todos[i].used && todos[i].id==id) return &todos[i]; } return NULL; }
static User* add_user(const char *username,const char *password){ if(users_len==users_cap){ size_t nc=users_cap?users_cap*2:8; User *nu=realloc(users,nc*sizeof(User)); if(!nu) return NULL; users=nu; users_cap=nc;} User u={0}; u.id=next_user_id++; u.username=strdup_s(username); u.password=strdup_s(password); if(!u.username||!u.password){ free(u.username); free(u.password); return NULL;} users[users_len++]=u; return &users[users_len-1]; }
static Session* add_session(int user_id){ if(sessions_len==sessions_cap){ size_t nc=sessions_cap?sessions_cap*2:8; Session *ns=realloc(sessions,nc*sizeof(Session)); if(!ns) return NULL; sessions=ns; sessions_cap=nc;} unsigned char rnd[32]; if(secure_random_bytes(rnd,sizeof(rnd))!=0) return NULL; Session s={0}; bytes_to_hex(rnd,sizeof(rnd),s.token); s.user_id=user_id; s.used=1; sessions[sessions_len++]=s; return &sessions[sessions_len-1]; }
static Todo* add_todo(int user_id,const char *title,const char *description){ if(todos_len==todos_cap){ size_t nc=todos_cap?todos_cap*2:16; Todo *nt=realloc(todos,nc*sizeof(Todo)); if(!nt) return NULL; todos=nt; todos_cap=nc;} Todo t={0}; t.id=next_todo_id++; t.user_id=user_id; t.title=strdup_s(title?title:""); t.description=strdup_s(description?description:""); t.completed=0; http_time_now_iso(t.created_at); memcpy(t.updated_at,t.created_at,sizeof(t.created_at)); t.used=1; if(!t.title||!t.description){ free(t.title); free(t.description); return NULL;} todos[todos_len++]=t; return &todos[todos_len-1]; }
static int delete_todo(Todo *todo){ if(!todo) return 0; todo->used=0; free(todo->title); todo->title=NULL; free(todo->description); todo->description=NULL; return 1; }

typedef struct { char *name; char *value; } HeaderKV; 

typedef struct { char method[8]; char path[256]; int content_length; HeaderKV *headers; size_t headers_len, headers_cap; char *body; } HttpRequest;

static void headers_add(HttpRequest *req,const char *name,const char *value){ if(req->headers_len==req->headers_cap){ size_t nc=req->headers_cap?req->headers_cap*2:16; HeaderKV *nh=realloc(req->headers,nc*sizeof(HeaderKV)); if(!nh) return; req->headers=nh; req->headers_cap=nc;} req->headers[req->headers_len].name=strdup_s(name); req->headers[req->headers_len].value=strdup_s(value); req->headers_len++; }
static const char* header_get(const HttpRequest *req,const char *name){ for(size_t i=0;i<req->headers_len;i++){ if(strcasecmp(req->headers[i].name,name)==0) return req->headers[i].value; } return NULL; }
static void headers_free(HttpRequest *req){ for(size_t i=0;i<req->headers_len;i++){ free(req->headers[i].name); free(req->headers[i].value);} free(req->headers);} 

static char* extract_cookie_session_id(const char *cookie_header){ if(!cookie_header) return NULL; char *dup=strdup(cookie_header); if(!dup) return NULL; char *p=dup; while(*p){ char *semi=strchr(p,';'); size_t tok_len= semi ? (size_t)(semi-p) : strlen(p); size_t i=0; while(i<tok_len && isspace((unsigned char)p[i])) i++; char *tok=p+i; size_t rem=tok_len-i; char *eq=memchr(tok,'=',rem); if(eq){ size_t name_len=(size_t)(eq-tok); while(name_len>0 && isspace((unsigned char)tok[name_len-1])) name_len--; if(name_len==strlen("session_id") && strncasecmp(tok,"session_id",name_len)==0){ char *val=eq+1; size_t val_len=rem-(size_t)(val-tok); while(val_len>0 && isspace((unsigned char)val[val_len-1])) val_len--; char *out=malloc(val_len+1); if(!out){ free(dup); return NULL;} memcpy(out,val,val_len); out[val_len]='\0'; free(dup); return out; } } if(!semi) break; p=semi+1; } free(dup); return NULL; }

static void send_response(int client_fd,int status,const char *status_text,const char *body,const char *extra_headers,int include_content_type){ char header[1024]; size_t body_len= body?strlen(body):0; char ct[64]=""; if(include_content_type){ snprintf(ct,sizeof(ct),"Content-Type: application/json\r\n"); } snprintf(header,sizeof(header),"HTTP/1.1 %d %s\r\nConnection: close\r\n%sContent-Length: %zu\r\n%s\r\n", status,status_text,ct,body_len, extra_headers?extra_headers:""); send(client_fd,header,strlen(header),0); if(body_len>0) send(client_fd,body,body_len,0); }
static void send_error_json(int client_fd,int status,const char *status_text,const char *msg){ json_t *o=json_object(); json_object_set_new(o,"error",json_string(msg)); char *dump=json_dumps(o,JSON_COMPACT); json_decref(o); if(!dump) dump=strdup("{}"); send_response(client_fd,status,status_text,dump,NULL,1); free(dump);} 

static int require_auth_fd(int client_fd,const HttpRequest *req,User **out_user){ const char *cookie=header_get(req,"Cookie"); if(!cookie){ // Try lowercase just in case
        cookie = header_get(req, "cookie");
    }
    if(!cookie){ send_error_json(client_fd,401,"Unauthorized","Authentication required"); return -1; }
    char *sid=extract_cookie_session_id(cookie); if(!sid){ send_error_json(client_fd,401,"Unauthorized","Authentication required"); return -1; } Session *s=find_session_by_token(sid); if(!s){ free(sid); send_error_json(client_fd,401,"Unauthorized","Authentication required"); return -1; } User *u=find_user_by_id(s->user_id); if(!u){ free(sid); send_error_json(client_fd,401,"Unauthorized","Authentication required"); return -1; } if(out_user) *out_user=u; free(sid); return 0; }

static void json_add_user_brief(json_t *o,const User *u){ json_object_set_new(o,"id",json_integer(u->id)); json_object_set_new(o,"username",json_string(u->username)); }
static json_t* json_todo(const Todo *t){ json_t *o=json_object(); json_object_set_new(o,"id",json_integer(t->id)); json_object_set_new(o,"title",json_string(t->title?t->title:"")); json_object_set_new(o,"description",json_string(t->description?t->description:"")); json_object_set_new(o,"completed",json_boolean(t->completed)); json_object_set_new(o,"created_at",json_string(t->created_at)); json_object_set_new(o,"updated_at",json_string(t->updated_at)); return o; }

static void handle_register(int client_fd,const HttpRequest *req){ json_error_t jerr; json_t *root=json_loads(req->body?req->body:"",0,&jerr); if(!root||!json_is_object(root)){ if(root) json_decref(root); send_error_json(client_fd,400,"Bad Request","Invalid JSON"); return;} const char *username=NULL,*password=NULL; json_t *ju=json_object_get(root,"username"); json_t *jp=json_object_get(root,"password"); if(json_is_string(ju)) username=json_string_value(ju); if(json_is_string(jp)) password=json_string_value(jp); if(!is_valid_username(username)){ json_decref(root); send_error_json(client_fd,400,"Bad Request","Invalid username"); return;} if(!is_valid_password(password)){ json_decref(root); send_error_json(client_fd,400,"Bad Request","Password too short"); return;} if(find_user_by_username(username)){ json_decref(root); send_error_json(client_fd,409,"Conflict","Username already exists"); return;} User *u=add_user(username,password); json_decref(root); if(!u){ send_error_json(client_fd,500,"Internal Server Error","Server error"); return;} json_t *o=json_object(); json_add_user_brief(o,u); char *dump=json_dumps(o,JSON_COMPACT); json_decref(o); if(!dump) dump=strdup("{}"); send_response(client_fd,201,"Created",dump,NULL,1); free(dump);} 

static void handle_login(int client_fd,const HttpRequest *req){ json_error_t jerr; json_t *root=json_loads(req->body?req->body:"",0,&jerr); if(!root||!json_is_object(root)){ if(root) json_decref(root); send_error_json(client_fd,400,"Bad Request","Invalid JSON"); return;} const char *username=NULL,*password=NULL; json_t *ju=json_object_get(root,"username"); json_t *jp=json_object_get(root,"password"); if(json_is_string(ju)) username=json_string_value(ju); if(json_is_string(jp)) password=json_string_value(jp); User *u=NULL; if(username) u=find_user_by_username(username); if(!u||!password||strcmp(u->password,password)!=0){ json_decref(root); send_error_json(client_fd,401,"Unauthorized","Invalid credentials"); return;} Session *s=add_session(u->id); if(!s){ json_decref(root); send_error_json(client_fd,500,"Internal Server Error","Server error"); return;} json_t *o=json_object(); json_add_user_brief(o,u); char *dump=json_dumps(o,JSON_COMPACT); json_decref(o); if(!dump) dump=strdup("{}"); char extra[256]; snprintf(extra,sizeof(extra),"Set-Cookie: session_id=%s; Path=/; HttpOnly\r\n", s->token); send_response(client_fd,200,"OK",dump,extra,1); free(dump); json_decref(root);} 

static void handle_logout(int client_fd,const HttpRequest *req){ const char *cookie=header_get(req,"Cookie"); if(!cookie) cookie=header_get(req,"cookie"); char *sid=extract_cookie_session_id(cookie); if(!sid){ send_error_json(client_fd,401,"Unauthorized","Authentication required"); return;} Session *s=find_session_by_token(sid); if(!s){ free(sid); send_error_json(client_fd,401,"Unauthorized","Authentication required"); return;} remove_session_by_token(sid); free(sid); send_response(client_fd,200,"OK","{}",NULL,1);} 

static void handle_me(int client_fd,const HttpRequest *req){ User *u=NULL; if(require_auth_fd(client_fd,req,&u)!=0) return; json_t *o=json_object(); json_add_user_brief(o,u); char *dump=json_dumps(o,JSON_COMPACT); json_decref(o); if(!dump) dump=strdup("{}"); send_response(client_fd,200,"OK",dump,NULL,1); free(dump);} 

static void handle_password(int client_fd,const HttpRequest *req){ User *u=NULL; if(require_auth_fd(client_fd,req,&u)!=0) return; json_error_t jerr; json_t *root=json_loads(req->body?req->body:"",0,&jerr); if(!root||!json_is_object(root)){ if(root) json_decref(root); send_error_json(client_fd,400,"Bad Request","Invalid JSON"); return;} const char *oldp=NULL,*newp=NULL; json_t *jo=json_object_get(root,"old_password"); json_t *jn=json_object_get(root,"new_password"); if(json_is_string(jo)) oldp=json_string_value(jo); if(json_is_string(jn)) newp=json_string_value(jn); if(!oldp||strcmp(u->password,oldp)!=0){ json_decref(root); send_error_json(client_fd,401,"Unauthorized","Invalid credentials"); return;} if(!is_valid_password(newp)){ json_decref(root); send_error_json(client_fd,400,"Bad Request","Password too short"); return;} free(u->password); u->password=strdup_s(newp); json_decref(root); if(!u->password){ send_error_json(client_fd,500,"Internal Server Error","Server error"); return;} send_response(client_fd,200,"OK","{}",NULL,1);} 

static void handle_todos_list(int client_fd,const HttpRequest *req){ User *u=NULL; if(require_auth_fd(client_fd,req,&u)!=0) return; json_t *arr=json_array(); for(size_t i=0;i<todos_len;i++){ if(todos[i].used && todos[i].user_id==u->id){ json_array_append_new(arr,json_todo(&todos[i])); } } char *dump=json_dumps(arr,JSON_COMPACT); json_decref(arr); if(!dump) dump=strdup("[]"); send_response(client_fd,200,"OK",dump,NULL,1); free(dump);} 

static void handle_todos_create(int client_fd,const HttpRequest *req){ User *u=NULL; if(require_auth_fd(client_fd,req,&u)!=0) return; json_error_t jerr; json_t *root=json_loads(req->body?req->body:"",0,&jerr); if(!root||!json_is_object(root)){ if(root) json_decref(root); send_error_json(client_fd,400,"Bad Request","Invalid JSON"); return;} const char *title=NULL; const char *description=""; json_t *jt=json_object_get(root,"title"); if(json_is_string(jt)) title=json_string_value(jt); json_t *jd=json_object_get(root,"description"); if(json_is_string(jd)) description=json_string_value(jd); if(!title||strlen(title)==0){ json_decref(root); send_error_json(client_fd,400,"Bad Request","Title is required"); return;} Todo *t=add_todo(u->id,title,description); json_decref(root); if(!t){ send_error_json(client_fd,500,"Internal Server Error","Server error"); return;} json_t *o=json_todo(t); char *dump=json_dumps(o,JSON_COMPACT); json_decref(o); if(!dump) dump=strdup("{}"); send_response(client_fd,201,"Created",dump,NULL,1); free(dump);} 

static int parse_todo_id(const char *path){ if(strncmp(path,"/todos/",8)!=0) return -1; const char *idstr=path+8; if(!*idstr) return -1; char *end=NULL; long v=strtol(idstr,&end,10); if(end==idstr||*end!='\0'||v<=0||v>2147483647L) return -1; return (int)v; }

static void handle_todos_get(int client_fd,const HttpRequest *req){ User *u=NULL; if(require_auth_fd(client_fd,req,&u)!=0) return; int id=parse_todo_id(req->path); if(id<0){ send_error_json(client_fd,404,"Not Found","Todo not found"); return;} Todo *t=find_todo_by_id(id); if(!t||t->user_id!=u->id){ send_error_json(client_fd,404,"Not Found","Todo not found"); return;} json_t *o=json_todo(t); char *dump=json_dumps(o,JSON_COMPACT); json_decref(o); if(!dump) dump=strdup("{}"); send_response(client_fd,200,"OK",dump,NULL,1); free(dump);} 

static void handle_todos_update(int client_fd,const HttpRequest *req){ User *u=NULL; if(require_auth_fd(client_fd,req,&u)!=0) return; int id=parse_todo_id(req->path); if(id<0){ send_error_json(client_fd,404,"Not Found","Todo not found"); return;} Todo *t=find_todo_by_id(id); if(!t||t->user_id!=u->id){ send_error_json(client_fd,404,"Not Found","Todo not found"); return;} json_error_t jerr; json_t *root=json_loads(req->body?req->body:"",0,&jerr); if(!root||!json_is_object(root)){ if(root) json_decref(root); send_error_json(client_fd,400,"Bad Request","Invalid JSON"); return;} json_t *jt=json_object_get(root,"title"); json_t *jd=json_object_get(root,"description"); json_t *jc=json_object_get(root,"completed"); if(jt && json_is_string(jt)){ const char *nt=json_string_value(jt); if(strlen(nt)==0){ json_decref(root); send_error_json(client_fd,400,"Bad Request","Title is required"); return;} free(t->title); t->title=strdup_s(nt); if(!t->title){ json_decref(root); send_error_json(client_fd,500,"Internal Server Error","Server error"); return;} } if(jd && json_is_string(jd)){ const char *nd=json_string_value(jd); free(t->description); t->description=strdup_s(nd); if(!t->description){ json_decref(root); send_error_json(client_fd,500,"Internal Server Error","Server error"); return;} } if(jc && json_is_boolean(jc)){ t->completed=json_is_true(jc)?1:0; } http_time_now_iso(t->updated_at); json_decref(root); json_t *o=json_todo(t); char *dump=json_dumps(o,JSON_COMPACT); json_decref(o); if(!dump) dump=strdup("{}"); send_response(client_fd,200,"OK",dump,NULL,1); free(dump);} 

static void handle_todos_delete(int client_fd,const HttpRequest *req){ User *u=NULL; if(require_auth_fd(client_fd,req,&u)!=0) return; int id=parse_todo_id(req->path); if(id<0){ send_error_json(client_fd,404,"Not Found","Todo not found"); return;} Todo *t=find_todo_by_id(id); if(!t||t->user_id!=u->id){ send_error_json(client_fd,404,"Not Found","Todo not found"); return;} delete_todo(t); const char *header="HTTP/1.1 204 No Content\r\nConnection: close\r\n\r\n"; send(client_fd,header,strlen(header),0);} 

static int recv_all_headers(int fd,char *buf,size_t max_len,size_t *out_len){ size_t total=0; while(total+1<max_len){ ssize_t r=recv(fd,buf+total,max_len-total-1,0); if(r<0){ if(errno==EINTR) continue; return -1;} if(r==0) return -1; total+=(size_t)r; buf[total]='\0'; if(strstr(buf,"\r\n\r\n")){ *out_len=total; return 0;} if(total>=MAX_HEADER_SIZE) return -1; } return -1; }

static int parse_request(int fd,HttpRequest *req){ char header_buf[MAX_HEADER_SIZE+1]; size_t hdr_len=0; if(recv_all_headers(fd,header_buf,sizeof(header_buf)-1,&hdr_len)!=0) return -1; header_buf[hdr_len]='\0'; char *hdr_end=strstr(header_buf,"\r\n\r\n"); if(!hdr_end) return -1; size_t header_only_len=(size_t)(hdr_end - header_buf)+4; char *line_end=strstr(header_buf,"\r\n"); if(!line_end) return -1; *line_end='\0'; char method[8]={0}, path[256]={0}; if(sscanf(header_buf,"%7s %255s",method,path)!=2) return -1; strncpy(req->method,method,sizeof(req->method)-1); strncpy(req->path,path,sizeof(req->path)-1); char *p=line_end+2; while(p < header_buf + header_only_len - 2){ char *e=strstr(p,"\r\n"); if(!e) break; *e='\0'; char *colon=strchr(p,':'); if(colon){ *colon='\0'; char *name=p; char *value=colon+1; while(*value==' ') value++; headers_add(req,name,value);} p=e+2; }
    const char *cl=header_get(req,"Content-Length"); int content_length=0; if(cl){ content_length=atoi(cl); if(content_length<0 || content_length>MAX_BODY_SIZE) return -1; } req->content_length=content_length; size_t already=hdr_len - header_only_len; char *body=NULL; if(content_length>0){ body=malloc((size_t)content_length+1); if(!body) return -1; size_t to_copy= already > (size_t)content_length ? (size_t)content_length : already; if(to_copy>0) memcpy(body,hdr_end+4,to_copy); size_t got=to_copy; while(got < (size_t)content_length){ ssize_t r=recv(fd,body+got,(size_t)content_length-got,0); if(r<0){ if(errno==EINTR) continue; free(body); return -1;} if(r==0){ free(body); return -1;} got+=(size_t)r; } body[content_length]='\0'; } req->body=body; return 0; }

static void free_request(HttpRequest *req){ headers_free(req); free(req->body);} 

static void route_request(int client_fd,const HttpRequest *req){ if(strcmp(req->method,"POST")==0 && strcmp(req->path,"/register")==0){ handle_register(client_fd,req); } else if(strcmp(req->method,"POST")==0 && strcmp(req->path,"/login")==0){ handle_login(client_fd,req);} else if(strcmp(req->method,"POST")==0 && strcmp(req->path,"/logout")==0){ handle_logout(client_fd,req);} else if(strcmp(req->method,"GET")==0 && strcmp(req->path,"/me")==0){ handle_me(client_fd,req);} else if(strcmp(req->method,"PUT")==0 && strcmp(req->path,"/password")==0){ handle_password(client_fd,req);} else if(strcmp(req->method,"GET")==0 && strcmp(req->path,"/todos")==0){ handle_todos_list(client_fd,req);} else if(strcmp(req->method,"POST")==0 && strcmp(req->path,"/todos")==0){ handle_todos_create(client_fd,req);} else if(strncmp(req->path,"/todos/",8)==0){ if(strcmp(req->method,"GET")==0){ handle_todos_get(client_fd,req);} else if(strcmp(req->method,"PUT")==0){ handle_todos_update(client_fd,req);} else if(strcmp(req->method,"DELETE")==0){ handle_todos_delete(client_fd,req);} else { send_error_json(client_fd,405,"Method Not Allowed","Method not allowed"); } } else { send_error_json(client_fd,404,"Not Found","Not found"); } }

int main(int argc,char *argv[]){ signal(SIGPIPE,SIG_IGN); int port=8080; for(int i=1;i<argc;i++){ if(strcmp(argv[i],"--port")==0 && i+1<argc){ port=atoi(argv[i+1]); i++; } }
    int server_fd=socket(AF_INET,SOCK_STREAM,0); if(server_fd<0){ perror("socket"); return 1;} int opt=1; setsockopt(server_fd,SOL_SOCKET,SO_REUSEADDR,&opt,sizeof(opt)); struct sockaddr_in addr; memset(&addr,0,sizeof(addr)); addr.sin_family=AF_INET; addr.sin_addr.s_addr=htonl(INADDR_ANY); addr.sin_port=htons((uint16_t)port); if(bind(server_fd,(struct sockaddr*)&addr,sizeof(addr))<0){ perror("bind"); close(server_fd); return 1;} if(listen(server_fd,64)<0){ perror("listen"); close(server_fd); return 1;} printf("Server listening on 0.0.0.0:%d\n",port); fflush(stdout); while(1){ struct sockaddr_in cli; socklen_t clilen=sizeof(cli); int cfd=accept(server_fd,(struct sockaddr*)&cli,&clilen); if(cfd<0){ if(errno==EINTR) continue; perror("accept"); break; } HttpRequest req; memset(&req,0,sizeof(req)); req.content_length=0; if(parse_request(cfd,&req)==0){ route_request(cfd,&req); free_request(&req);} else { const char *resp="HTTP/1.1 400 Bad Request\r\nConnection: close\r\nContent-Type: application/json\r\nContent-Length: 24\r\n\r\n{\"error\":\"Bad request\"}"; send(cfd,resp,strlen(resp),0);} close(cfd);} close(server_fd); return 0; }
